apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: poc-ns
spec:
  strategy:
    type: Recreate
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: backend
        image: bdineshchary/devopsproj
        ports:
        - containerPort: 8443

---
apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: poc-ns
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
  - port: 8443
    targetPort: 8443
