apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: poc-ns
spec:
  strategy:
    type: Recreate
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: backend
        image: 145988340565.dkr.ecr.us-west-2.amazonaws.com/asg
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: poc-ns
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
  - port: 8080
    targetPort: 8080
